db.url=jdbc:postgresql://localhost:5432/test
db.username=test
db.password=test

api.youtube.url=https://www.googleapis.com/youtube/v3/videos
api.rutube.url=https://rutube.ru/api/video
api.vimeo.url=https://api.vimeo.com/videos

api.youtube.token=
api.rutube.token=
api.vimeo.token=
