db.url=jdbc:postgresql://localhost:5432/test
db.username=test
db.password=test

api.youtube.url=https://www.googleapis.com/youtube/v3/videos
api.rutube.url=https://rutube/api
api.vimeo.url=https://vimeo/api

api.youtube.token=AIzaSyCg3fvUFxSdtcHqOJqhFvl6ghmOiMF_ipY&id
api.rutube.token=
api.vimeo.token=