db.url=jdbc:postgresql://localhost:5433/hakaton_db
db.username=hakaton_user
db.password=hakaton_password

api.youtube.url=https://www.googleapis.com/youtube/v3/videos
api.rutube.url=https://rutube.ru/api/video
api.vimeo.url=

api.youtube.token=AIzaSyCg3fvUFxSdtcHqOJqhFvl6ghmOiMF_ipY
api.rutube.token=
api.vimeo.token=